// swift-tools-version: 5.9
// Generated by flutter-tvos. Do not edit.
//
// Vends the tvOS Flutter engine (Flutter.xcframework) to the Swift package
// graph so federated plugin targets can `import Flutter` without declaring a
// dependency of their own.
import PackageDescription

let package = Package(
  name: "FlutterFramework",
  products: [
    .library(name: "FlutterFramework", targets: ["FlutterFramework"]),
  ],
  targets: [
    .binaryTarget(name: "FlutterFramework", path: "Flutter.xcframework"),
  ]
)
