// swift-tools-version: 5.9
// Generated by flutter-tvos. Do not edit.
import PackageDescription

let package = Package(
  name: "FlutterGeneratedPluginSwiftPackage",
  platforms: [
    .tvOS("13.0"),
  ],
  products: [
    .library(name: "FlutterGeneratedPluginSwiftPackage", type: .static, targets: ["FlutterGeneratedPluginSwiftPackage"]),
  ],
  dependencies: [
    .package(name: "FlutterFramework", path: ".packages/FlutterFramework"),
  ],
  targets: [
    .target(
      name: "FlutterGeneratedPluginSwiftPackage",
      dependencies: [
        .product(name: "FlutterFramework", package: "FlutterFramework"),
      ]
    ),
  ]
)
